github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true

image: gitpod/workspace-full:latest

tasks:
  - name: Workshop Setup
    init: |
      npm install
      npx playwright install chromium
      npm install -g @anthropic-ai/claude-code
    command: |
      chmod +x welcome.sh
      bash welcome.sh

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - anthropic.claude-dev
    - google.gemini-code-assist
