image:
  file: .gitpod.Dockerfile

tasks:
  - name: Ready to Code
    init: |
      # Link the pre-baked node_modules to the local folder
      # This makes 'npm install' unnecessary
      ln -s /home/gitpod/prebuild/node_modules .
    command: |
      clear
      echo "🚀 WELCOME TO THE WORKSHOP"
      echo "✅ Claude Code & 30+ Dependencies are PRE-INSTALLED."
      echo "----------------------------------------------------"
      claude --version

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public # No more Localhost 404 issues
